name: flutter_duit
description: Server driver UI framework for Flutter. Allows you to update your cool UI without updating the app!
version: 3.6.0
repository: https://github.com/Duit-Foundation/flutter_duit
issue_tracker: https://github.com/Duit-Foundation/flutter_duit/issues
homepage: https://duit.pro/en/

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  duit_kernel:
    git:
      url: https://github.com/Duit-Foundation/duit_kernel.git
      ref: v4
  flutter:
    sdk: flutter
  http: ^1.3.0
  meta: ^1.15.0
  talker: ^4.9.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
